frequency : 15.0
scan_topic : scan
max_line_gap : 0.5
min_line_length : 0.15
min_range : 0.3
min_split_dist : 0.05
outlier_dist : 0.05
min_line_points : 10
max_distance_in_line : 0.005
max_point_coincide : 0.2
