- {name: use_range_weight, type: bool, min: , max: , default: true}
- {name: bad_laser_check, type: bool, min: , max: , default: false}
- {name: bad_laser_range_min, type: double, min: 0.001, max: 1.5, default: 0.3}
- {name: bad_laser_range_max, type: double, min: 5, max: 100, default: 10}
- {name: bad_laser_range_rate, type: double, min: 0, max: 1, default: 0.6}