- {name: map_update_interval, type: double, min: 0.1,max: 60, default: 5.0}
- {name: iterations, type: int, min: 0, max: 20, default: 5}
- {name: minimumScore, type: double, min: 0, max: 1000, default: 0}
- {name: srr, type: double, min: 0, max: 10, default: 0.1}
- {name: srt, type: double, min: 0, max: 10, default: 0.2}
- {name: str, type: double, min: 0, max: 10, default: 0.1}
- {name: stt, type: double, min: 0, max: 10, default: 0.2}
- {name: temporalUpdate, type: double, min: -1.0, max: 10, default: -1.0}
- {name: particles, type: int, min: 0, max: 100, default: 30}
- {name: xmin, type: double, min: -200.0, max: 0, default: -100.0}
- {name: ymin, type: double, min: -200.0, max: 0, default: -100.0}
- {name: xmax, type: double, min: 0, max: 200.0, default: 100.0}
- {name: ymax, type: double, min: 0, max: 200.0, default: 100.0}
- {name: delta, type: double, min: 0.01, max: 0.1, default: 0.05}