cov_y: 0.04
max_offset_with_currentpose: 2.5
update_min_distance: 2.5
update_rate: 20.0
max_diff_range_self: 0.1
is_use_uwb: false
cov_th: 0.68
timer_duration: 2.0
is_use_map: true
cov_x: 0.04
timer_max_offset: 0.1