// Generated by gencpp from file robot_state_keeper/RegisterStateResponse.msg
// DO NOT EDIT!


#ifndef ROBOT_STATE_KEEPER_MESSAGE_REGISTERSTATERESPONSE_H
#define ROBOT_STATE_KEEPER_MESSAGE_REGISTERSTATERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_state_keeper
{
template <class ContainerAllocator>
struct RegisterStateResponse_
{
  typedef RegisterStateResponse_<ContainerAllocator> Type;

  RegisterStateResponse_()
    : error_code(0)  {
    }
  RegisterStateResponse_(const ContainerAllocator& _alloc)
    : error_code(0)  {
  (void)_alloc;
    }



   typedef uint32_t _error_code_type;
  _error_code_type error_code;




  typedef boost::shared_ptr< ::robot_state_keeper::RegisterStateResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_state_keeper::RegisterStateResponse_<ContainerAllocator> const> ConstPtr;

}; // struct RegisterStateResponse_

typedef ::robot_state_keeper::RegisterStateResponse_<std::allocator<void> > RegisterStateResponse;

typedef boost::shared_ptr< ::robot_state_keeper::RegisterStateResponse > RegisterStateResponsePtr;
typedef boost::shared_ptr< ::robot_state_keeper::RegisterStateResponse const> RegisterStateResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_state_keeper::RegisterStateResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_state_keeper::RegisterStateResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robot_state_keeper

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'robot_state_keeper': ['/home/paul/newcode/catkin_ws/src/robot_state_keeper/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robot_state_keeper::RegisterStateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_state_keeper::RegisterStateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_state_keeper::RegisterStateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_state_keeper::RegisterStateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_state_keeper::RegisterStateResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_state_keeper::RegisterStateResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_state_keeper::RegisterStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "caf727fd8154dfaab2a64cb6ae162cc9";
  }

  static const char* value(const ::robot_state_keeper::RegisterStateResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcaf727fd8154dfaaULL;
  static const uint64_t static_value2 = 0xb2a64cb6ae162cc9ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_state_keeper::RegisterStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_state_keeper/RegisterStateResponse";
  }

  static const char* value(const ::robot_state_keeper::RegisterStateResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_state_keeper::RegisterStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 error_code\n\
\n\
";
  }

  static const char* value(const ::robot_state_keeper::RegisterStateResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_state_keeper::RegisterStateResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.error_code);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct RegisterStateResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_state_keeper::RegisterStateResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_state_keeper::RegisterStateResponse_<ContainerAllocator>& v)
  {
    s << indent << "error_code: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.error_code);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_STATE_KEEPER_MESSAGE_REGISTERSTATERESPONSE_H
