// Generated by gencpp from file robot_state_keeper/robot_state.msg
// DO NOT EDIT!


#ifndef ROBOT_STATE_KEEPER_MESSAGE_ROBOT_STATE_H
#define ROBOT_STATE_KEEPER_MESSAGE_ROBOT_STATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_state_keeper
{
template <class ContainerAllocator>
struct robot_state_
{
  typedef robot_state_<ContainerAllocator> Type;

  robot_state_()
    : enabled(0)
    , error_code(0)
    , name()
    , info()  {
    }
  robot_state_(const ContainerAllocator& _alloc)
    : enabled(0)
    , error_code(0)
    , name(_alloc)
    , info(_alloc)  {
    }



   typedef uint32_t _enabled_type;
  _enabled_type enabled;

   typedef uint32_t _error_code_type;
  _error_code_type error_code;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _info_type;
  _info_type info;




  typedef boost::shared_ptr< ::robot_state_keeper::robot_state_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_state_keeper::robot_state_<ContainerAllocator> const> ConstPtr;

}; // struct robot_state_

typedef ::robot_state_keeper::robot_state_<std::allocator<void> > robot_state;

typedef boost::shared_ptr< ::robot_state_keeper::robot_state > robot_statePtr;
typedef boost::shared_ptr< ::robot_state_keeper::robot_state const> robot_stateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_state_keeper::robot_state_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_state_keeper::robot_state_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robot_state_keeper

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'robot_state_keeper': ['/home/robot/catkin_ws/src/robot_state_keeper/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robot_state_keeper::robot_state_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_state_keeper::robot_state_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_state_keeper::robot_state_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_state_keeper::robot_state_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_state_keeper::robot_state_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_state_keeper::robot_state_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_state_keeper::robot_state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ca5dbf5ea996407f591dd5dc3f38a3c4";
  }

  static const char* value(const ::robot_state_keeper::robot_state_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xca5dbf5ea996407fULL;
  static const uint64_t static_value2 = 0x591dd5dc3f38a3c4ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_state_keeper::robot_state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_state_keeper/robot_state";
  }

  static const char* value(const ::robot_state_keeper::robot_state_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_state_keeper::robot_state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 enabled\n\
uint32 error_code\n\
string name\n\
string info\n\
\n\
";
  }

  static const char* value(const ::robot_state_keeper::robot_state_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_state_keeper::robot_state_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.enabled);
      stream.next(m.error_code);
      stream.next(m.name);
      stream.next(m.info);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct robot_state_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_state_keeper::robot_state_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_state_keeper::robot_state_<ContainerAllocator>& v)
  {
    s << indent << "enabled: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.enabled);
    s << indent << "error_code: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.error_code);
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "info: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.info);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_STATE_KEEPER_MESSAGE_ROBOT_STATE_H
