controller_costmap:
  global_frame: odom
  robot_base_frame: base_link
  plugins:
     - {name: sonar_all_layer,   type: "range_sensor_layer::SonarSensorLayer"}
     #- {name: laser_all_layer,   type: "range_sensor_layer::SonarSensorLayer"}
     - {name: obstacle_layer,   type: "costmap_2d::ObstacleLayer"}
     - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
  track_unknown_space: false
  update_frequency: 10.0
  publish_frequency: 1.0
  static_map: false
  virtual_layer: false
  rolling_window: true
  width: 3.0
  height: 3.0
  resolution: 0.025

  unknown_cost_value: 205

  obstacle_layer: 
     combination_method: 1
     observation_sources: scan 
     scan: 
        sensor_frame: laser
        data_type: LaserScan
        topic: scan_filtered
        marking: true
        clearing: true 
        inf_is_valid: true

  inflation_layer:
     enabled: true
     inflation_radius: 0.025

  sonar_all_layer:
     topics: ["/sonar_msg_all"]
     no_readings_timeout: 0.0
     keep_time: 2.0

  laser_all_layer:
     topics: ["/laser_msg_all"]
     no_readings_timeout: 0.0
     keep_time: 2.0


