// Generated by gencpp from file gmapping/map_filter.msg
// DO NOT EDIT!


#ifndef GMAPPING_MESSAGE_MAP_FILTER_H
#define GMAPPING_MESSAGE_MAP_FILTER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <nav_msgs/MapMetaData.h>

namespace gmapping
{
template <class ContainerAllocator>
struct map_filter_
{
  typedef map_filter_<ContainerAllocator> Type;

  map_filter_()
    : header()
    , info()
    , data_free()
    , data_obstacle()  {
    }
  map_filter_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , info(_alloc)
    , data_free(_alloc)
    , data_obstacle(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::nav_msgs::MapMetaData_<ContainerAllocator>  _info_type;
  _info_type info;

   typedef std::vector<uint32_t, typename ContainerAllocator::template rebind<uint32_t>::other >  _data_free_type;
  _data_free_type data_free;

   typedef std::vector<uint32_t, typename ContainerAllocator::template rebind<uint32_t>::other >  _data_obstacle_type;
  _data_obstacle_type data_obstacle;




  typedef boost::shared_ptr< ::gmapping::map_filter_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gmapping::map_filter_<ContainerAllocator> const> ConstPtr;

}; // struct map_filter_

typedef ::gmapping::map_filter_<std::allocator<void> > map_filter;

typedef boost::shared_ptr< ::gmapping::map_filter > map_filterPtr;
typedef boost::shared_ptr< ::gmapping::map_filter const> map_filterConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gmapping::map_filter_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gmapping::map_filter_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace gmapping

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'nav_msgs': ['/opt/ros/indigo/share/nav_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'gmapping': ['/home/paul/laser_slam/src/slam_gmapping/gmapping/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::gmapping::map_filter_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gmapping::map_filter_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gmapping::map_filter_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gmapping::map_filter_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gmapping::map_filter_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gmapping::map_filter_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gmapping::map_filter_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d910d9bfea680ca44f10132db23ab391";
  }

  static const char* value(const ::gmapping::map_filter_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd910d9bfea680ca4ULL;
  static const uint64_t static_value2 = 0x4f10132db23ab391ULL;
};

template<class ContainerAllocator>
struct DataType< ::gmapping::map_filter_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gmapping/map_filter";
  }

  static const char* value(const ::gmapping::map_filter_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gmapping::map_filter_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header \n\
nav_msgs/MapMetaData info\n\
uint32[] data_free\n\
uint32[] data_obstacle\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: nav_msgs/MapMetaData\n\
# This hold basic information about the characterists of the OccupancyGrid\n\
\n\
# The time at which the map was loaded\n\
time map_load_time\n\
# The map resolution [m/cell]\n\
float32 resolution\n\
# Map width [cells]\n\
uint32 width\n\
# Map height [cells]\n\
uint32 height\n\
# The origin of the map [m, m, rad].  This is the real-world pose of the\n\
# cell (0,0) in the map.\n\
geometry_msgs/Pose origin\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::gmapping::map_filter_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gmapping::map_filter_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.info);
      stream.next(m.data_free);
      stream.next(m.data_obstacle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct map_filter_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gmapping::map_filter_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gmapping::map_filter_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "info: ";
    s << std::endl;
    Printer< ::nav_msgs::MapMetaData_<ContainerAllocator> >::stream(s, indent + "  ", v.info);
    s << indent << "data_free[]" << std::endl;
    for (size_t i = 0; i < v.data_free.size(); ++i)
    {
      s << indent << "  data_free[" << i << "]: ";
      Printer<uint32_t>::stream(s, indent + "  ", v.data_free[i]);
    }
    s << indent << "data_obstacle[]" << std::endl;
    for (size_t i = 0; i < v.data_obstacle.size(); ++i)
    {
      s << indent << "  data_obstacle[" << i << "]: ";
      Printer<uint32_t>::stream(s, indent + "  ", v.data_obstacle[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // GMAPPING_MESSAGE_MAP_FILTER_H
