obstacle_range: 3.5
raytrace_range: 10.0
#robot_radius: 0.63
clearing: true
footprint_enable: true
footprint: [[0.57,0.15],[0.57, -0.15],[0.42,-0.265],[-0.54,-0.265],[-0.54,0.265],[0.42,0.265]]
#footprint: [[0.57,0.15],[0.57, -0.15],[0.42,-0.25],[-0.54,-0.25],[-0.54,0.25],[0.42,0.25]]
#footprint: [[0.57,0.15],[0.57, -0.15],[0.32,-0.34],[-0.60,-0.34],[-0.6,0.34],[0.32,0.34]]
#footprint: [[-0.55,-0.26],[-0.55, 0.26],[0.60,0.26],[0.60,-0.26]]
#footprint: [[0.13,0.24],[-0.15,0.28],[-0.43,0.24],[-0.43,-0.24],[-0.15,-0.28],[0.13,-0.24]]
#footprint: [[0.24,0.24],[-0.15,0.28],[-0.43,0.24],[-0.43,-0.24],[-0.15,-0.28],[0.24,-0.24]]
track_unknown_space: false
max_obstacle_height: 1.32
min_obstacle_height: 0.0

observation_sources: scan
scan: {sensor_frame: laser, data_type: LaserScan, topic: scan_filtered, marking: true, clearing: true ,inf_is_valid: true}

#observation_sources: rgbd
#rgbd: {sensor_frame: camera_depth_frame, data_type: PointCloud2, topic: /camera/depth/points, marking: true, clearing: true}


#observation_sources: obst
#obst: {sensor_frame: base_link, data_type: PointCloud2, topic: /obstacle_points, marking: true, clearing: true}

#observation_sources: scan obst
#obst: {sensor_frame: base_link, data_type: PointCloud2, topic: /obstacle_points, marking: true, clearing: true}
#scan: {sensor_frame: laser, data_type: LaserScan, topic: scan, marking: true, clearing: true}
#rgbd: {sensor_frame: camera_depth_frame, data_type: PointCloud2, topic: /camera/depth/points, marking: true, clearing: true}
