local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  plugins:
     #- {name: static_layer,   type: "costmap_2d::StaticLayer"}
     #- {name: sonar_layer,   type: "range_sensor_layer::RangeSensorLayer"}
     - {name: sonar_all_layer,   type: "range_sensor_layer::SonarSensorLayer"}
     #- {name: laser_all_layer,   type: "range_sensor_layer::SonarSensorLayer"}
     #- {name: laser_layer,   type: "costmap_2d::ObstacleLayer"}
     - {name: rgbd_layer,   type: "costmap_2d::RgbdVoxelLayer"}
     - {name: obstacle_layer,   type: "costmap_2d::ObstacleLayer"}
     - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
  update_frequency: 10.0
  publish_frequency: 1.0
  static_map: false
  virtual_layer: true
  rolling_window: true
  width: 6
  height: 6
  resolution: 0.05
  #save_debug_pgm: true
  unknown_cost_value: 205
  inflation_radius: 1.5
  cost_scaling_factor: 4
  forbidden_radius: 0.3
  circumscribed_radius: 0.2


  obstacle_layer: 
     combination_method: 1
     observation_sources: scan 
     scan: 
        sensor_frame: laser
        data_type: LaserScan
        topic: scan_filtered
        marking: true
        clearing: true 
        inf_is_valid: true

  laser_layer: 
     combination_method: 1
     obstacle_range: 1.0
     raytrace_range: 3.0
     observation_sources: obst
     obst: {data_type: PointCloud2, topic: lasercloud, observation_persistence: 0.25, marking: true, clearing: true}

  inflation_layer:
     enabled: true
     inflation_radius: 1.0

  sonar_layer:
     topics: ["/sonar_msg"]
     no_readings_timeout: 0.0

  sonar_all_layer:
     topics: ["/sonar_msg_all"]
     no_readings_timeout: 0.0
     keep_time: 5.0

  laser_all_layer:
     topics: ["/laser_msg_all"]
     no_readings_timeout: 0.0
     keep_time: 5.0

  rgbd_layer:
     voxel_observation_sources: camera/depth/points
     camera/depth/points:
        min_obstacle_height: 0.15
        max_obstacle_height: 1.0
        inf_is_valid: false
        clearing: true
        observation_keep_time: 1.0
        obstacle_range: 1.5

