// Generated by gencpp from file uwb_location/Anchor.msg
// DO NOT EDIT!


#ifndef UWB_LOCATION_MESSAGE_ANCHOR_H
#define UWB_LOCATION_MESSAGE_ANCHOR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace uwb_location
{
template <class ContainerAllocator>
struct Anchor_
{
  typedef Anchor_<ContainerAllocator> Type;

  Anchor_()
    : id(0)
    , distance(0.0)  {
    }
  Anchor_(const ContainerAllocator& _alloc)
    : id(0)
    , distance(0.0)  {
  (void)_alloc;
    }



   typedef uint32_t _id_type;
  _id_type id;

   typedef float _distance_type;
  _distance_type distance;




  typedef boost::shared_ptr< ::uwb_location::Anchor_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uwb_location::Anchor_<ContainerAllocator> const> ConstPtr;

}; // struct Anchor_

typedef ::uwb_location::Anchor_<std::allocator<void> > Anchor;

typedef boost::shared_ptr< ::uwb_location::Anchor > AnchorPtr;
typedef boost::shared_ptr< ::uwb_location::Anchor const> AnchorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uwb_location::Anchor_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uwb_location::Anchor_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace uwb_location

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'uwb_location': ['/home/robot/catkin_ws/src/uwb_location/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::uwb_location::Anchor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uwb_location::Anchor_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uwb_location::Anchor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uwb_location::Anchor_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uwb_location::Anchor_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uwb_location::Anchor_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uwb_location::Anchor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b531caca3e028127190a5ea4f8e00cce";
  }

  static const char* value(const ::uwb_location::Anchor_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb531caca3e028127ULL;
  static const uint64_t static_value2 = 0x190a5ea4f8e00cceULL;
};

template<class ContainerAllocator>
struct DataType< ::uwb_location::Anchor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uwb_location/Anchor";
  }

  static const char* value(const ::uwb_location::Anchor_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uwb_location::Anchor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 id\n\
float32 distance\n\
";
  }

  static const char* value(const ::uwb_location::Anchor_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uwb_location::Anchor_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Anchor_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uwb_location::Anchor_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::uwb_location::Anchor_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.id);
    s << indent << "distance: ";
    Printer<float>::stream(s, indent + "  ", v.distance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UWB_LOCATION_MESSAGE_ANCHOR_H
