// Generated by gencpp from file uwb_location/UwbAnchors.msg
// DO NOT EDIT!


#ifndef UWB_LOCATION_MESSAGE_UWBANCHORS_H
#define UWB_LOCATION_MESSAGE_UWBANCHORS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <uwb_location/Anchor.h>

namespace uwb_location
{
template <class ContainerAllocator>
struct UwbAnchors_
{
  typedef UwbAnchors_<ContainerAllocator> Type;

  UwbAnchors_()
    : header()
    , anchors()  {
    }
  UwbAnchors_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , anchors(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::uwb_location::Anchor_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::uwb_location::Anchor_<ContainerAllocator> >::other >  _anchors_type;
  _anchors_type anchors;




  typedef boost::shared_ptr< ::uwb_location::UwbAnchors_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uwb_location::UwbAnchors_<ContainerAllocator> const> ConstPtr;

}; // struct UwbAnchors_

typedef ::uwb_location::UwbAnchors_<std::allocator<void> > UwbAnchors;

typedef boost::shared_ptr< ::uwb_location::UwbAnchors > UwbAnchorsPtr;
typedef boost::shared_ptr< ::uwb_location::UwbAnchors const> UwbAnchorsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uwb_location::UwbAnchors_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uwb_location::UwbAnchors_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace uwb_location

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'uwb_location': ['/home/robot/catkin_ws/src/uwb_location/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::uwb_location::UwbAnchors_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uwb_location::UwbAnchors_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uwb_location::UwbAnchors_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uwb_location::UwbAnchors_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uwb_location::UwbAnchors_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uwb_location::UwbAnchors_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uwb_location::UwbAnchors_<ContainerAllocator> >
{
  static const char* value()
  {
    return "57e2b6158a0dbdc8adb4f066e41263e2";
  }

  static const char* value(const ::uwb_location::UwbAnchors_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x57e2b6158a0dbdc8ULL;
  static const uint64_t static_value2 = 0xadb4f066e41263e2ULL;
};

template<class ContainerAllocator>
struct DataType< ::uwb_location::UwbAnchors_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uwb_location/UwbAnchors";
  }

  static const char* value(const ::uwb_location::UwbAnchors_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uwb_location::UwbAnchors_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
Anchor[] anchors\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: uwb_location/Anchor\n\
uint32 id\n\
float32 distance\n\
";
  }

  static const char* value(const ::uwb_location::UwbAnchors_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uwb_location::UwbAnchors_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.anchors);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct UwbAnchors_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uwb_location::UwbAnchors_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::uwb_location::UwbAnchors_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "anchors[]" << std::endl;
    for (size_t i = 0; i < v.anchors.size(); ++i)
    {
      s << indent << "  anchors[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::uwb_location::Anchor_<ContainerAllocator> >::stream(s, indent + "    ", v.anchors[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // UWB_LOCATION_MESSAGE_UWBANCHORS_H
