- {name: min_particles, type: int, default: 500}
- {name: max_particles, type: int, default: 5000}
- {name: kld_err, type: double, default: 0.01}
- {name: kld_z, type: double, default: 0.99}
- {name: update_min_a, type: double, default: 0.15}
- {name: update_min_d, type: double, default: 0.2}
- {name: resample_interval, type: int, default: 2}
- {name: transform_tolerance, type: double, default: 0.1}
- {name: recovery_alpha_slow, type: double, default: 0}
- {name: recovery_alpha_fast, type: double, default: 0}
- {name: gui_publish_rate, type: double, default: 1.0}
- {name: use_map_topic, type: bool, default: true}
- {name: laser_max_beams, type: int, default: 300}
- {name: laser_z_hit, type: double, default: 0.98}
- {name: laser_z_short, type: double, default: 0.05}
- {name: laser_z_max, type: double, default: 0.02}
- {name: laser_z_rand, type: double, default: 0.05}
- {name: laser_sigma_hit, type: double, default: 0.1}
- {name: odom_alpha1, type: double, default: 1.0}
- {name: odom_alpha2, type: double, default: 0.2}
- {name: odom_alpha3, type: double, default: 0.5}
- {name: odom_alpha4, type: double, default: 0.05}
- {name: odom_alpha5, type: double, default: 0.1}
- {name: save_pose_rate, type: double, default: 1.0}
