min_particles: 500
max_particles: 5000
kld_err: 0.01
kld_z: 0.99
update_min_a: 0.15
update_min_d: 0.2
resample_interval: 2
transform_tolerance: 0.1
recovery_alpha_slow: 0.0
recovery_alpha_fast: 0.0
gui_publish_rate: 1.0
use_map_topic: true
laser_max_beams: 300
laser_z_max: 0.05
laser_z_hit: 0.98
laser_z_rand: 0.02
laser_z_short: 0.05
laser_sigma_hit: 0.1
odom_alpha1: 1.0
odom_alpha2: 0.2
odom_alpha3: 0.5
odom_alpha4: 0.05
odom_alpha5: 0.1
save_pose_rate: 1.0
