// Generated by gencpp from file map_server/query_uwb.msg
// DO NOT EDIT!


#ifndef MAP_SERVER_MESSAGE_QUERY_UWB_H
#define MAP_SERVER_MESSAGE_QUERY_UWB_H

#include <ros/service_traits.h>


#include <map_server/query_uwbRequest.h>
#include <map_server/query_uwbResponse.h>


namespace map_server
{

struct query_uwb
{

typedef query_uwbRequest Request;
typedef query_uwbResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct query_uwb
} // namespace map_server


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::map_server::query_uwb > {
  static const char* value()
  {
    return "e9286ec18b522eb2d4080cc59d54f4c7";
  }

  static const char* value(const ::map_server::query_uwb&) { return value(); }
};

template<>
struct DataType< ::map_server::query_uwb > {
  static const char* value()
  {
    return "map_server/query_uwb";
  }

  static const char* value(const ::map_server::query_uwb&) { return value(); }
};


// service_traits::MD5Sum< ::map_server::query_uwbRequest> should match 
// service_traits::MD5Sum< ::map_server::query_uwb > 
template<>
struct MD5Sum< ::map_server::query_uwbRequest>
{
  static const char* value()
  {
    return MD5Sum< ::map_server::query_uwb >::value();
  }
  static const char* value(const ::map_server::query_uwbRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::map_server::query_uwbRequest> should match 
// service_traits::DataType< ::map_server::query_uwb > 
template<>
struct DataType< ::map_server::query_uwbRequest>
{
  static const char* value()
  {
    return DataType< ::map_server::query_uwb >::value();
  }
  static const char* value(const ::map_server::query_uwbRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::map_server::query_uwbResponse> should match 
// service_traits::MD5Sum< ::map_server::query_uwb > 
template<>
struct MD5Sum< ::map_server::query_uwbResponse>
{
  static const char* value()
  {
    return MD5Sum< ::map_server::query_uwb >::value();
  }
  static const char* value(const ::map_server::query_uwbResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::map_server::query_uwbResponse> should match 
// service_traits::DataType< ::map_server::query_uwb > 
template<>
struct DataType< ::map_server::query_uwbResponse>
{
  static const char* value()
  {
    return DataType< ::map_server::query_uwb >::value();
  }
  static const char* value(const ::map_server::query_uwbResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MAP_SERVER_MESSAGE_QUERY_UWB_H
