// Generated by gencpp from file localization/localization_state.msg
// DO NOT EDIT!


#ifndef LOCALIZATION_MESSAGE_LOCALIZATION_STATE_H
#define LOCALIZATION_MESSAGE_LOCALIZATION_STATE_H

#include <ros/service_traits.h>


#include <localization/localization_stateRequest.h>
#include <localization/localization_stateResponse.h>


namespace localization
{

struct localization_state
{

typedef localization_stateRequest Request;
typedef localization_stateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct localization_state
} // namespace localization


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::localization::localization_state > {
  static const char* value()
  {
    return "af6d3a99f0fbeb66d3248fa4b3e675fb";
  }

  static const char* value(const ::localization::localization_state&) { return value(); }
};

template<>
struct DataType< ::localization::localization_state > {
  static const char* value()
  {
    return "localization/localization_state";
  }

  static const char* value(const ::localization::localization_state&) { return value(); }
};


// service_traits::MD5Sum< ::localization::localization_stateRequest> should match 
// service_traits::MD5Sum< ::localization::localization_state > 
template<>
struct MD5Sum< ::localization::localization_stateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::localization::localization_state >::value();
  }
  static const char* value(const ::localization::localization_stateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::localization::localization_stateRequest> should match 
// service_traits::DataType< ::localization::localization_state > 
template<>
struct DataType< ::localization::localization_stateRequest>
{
  static const char* value()
  {
    return DataType< ::localization::localization_state >::value();
  }
  static const char* value(const ::localization::localization_stateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::localization::localization_stateResponse> should match 
// service_traits::MD5Sum< ::localization::localization_state > 
template<>
struct MD5Sum< ::localization::localization_stateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::localization::localization_state >::value();
  }
  static const char* value(const ::localization::localization_stateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::localization::localization_stateResponse> should match 
// service_traits::DataType< ::localization::localization_state > 
template<>
struct DataType< ::localization::localization_stateResponse>
{
  static const char* value()
  {
    return DataType< ::localization::localization_state >::value();
  }
  static const char* value(const ::localization::localization_stateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LOCALIZATION_MESSAGE_LOCALIZATION_STATE_H
